export const MODAL_OPEN = "MODAL_OPEN"

export const PRODUCT_SELECTED = "EMPLOYEE_SELECTED"

// start product
export const PRODUCT_FETCH_REQUESTED = "PRODUCT_FETCH_REQUESTED"
export const PRODUCT_FETCH_SUCCEEDED = "PRODUCT_FETCH_SUCCEEDED"
export const PRODUCT_FETCH_FAILED = "PRODUCT_FETCH_FAILED"

export const PRODUCT_ADD_REQUESTED = "PRODUCT_ADD_REQUESTED"
export const PRODUCT_ADD_SUCCEEDED = "PRODUCT_ADD_SUCCEEDED"
export const PRODUCT_ADD_FAILED = "PRODUCT_ADD_FAILED"

export const PRODUCT_UPDATE_REQUESTED = "PRODUCT_UPDATE_REQUESTED"
export const PRODUCT_UPDATE_SUCCEEDED = "PRODUCT_UPDATE_SUCCEEDED"
export const PRODUCT_UPDATE_FAILED = "PRODUCT_UPDATE_FAILED"

export const PRODUCT_DELETE_REQUESTED = "PRODUCT_DELETE_REQUESTED"
export const PRODUCT_DELETE_SUCCEEDED = "PRODUCT_DELETE_SUCCEEDED"
export const PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED"

// start user
export const USER_FETCH_REQUESTED = "USER_FETCH_REQUESTED"
export const USER_FETCH_SUCCEEDED = "USER_FETCH_SUCCEEDED"
export const USER_FETCH_FAILED = "USER_FETCH_FAILED"

export const USER_ADD_REQUESTED = "USER_ADD_REQUESTED"
export const USER_ADD_SUCCEEDED = "USER_ADD_SUCCEEDED"
export const USER_ADD_FAILED = "USER_ADD_FAILED"

export const USER_UPDATE_REQUESTED = "USER_UPDATE_REQUESTED"
export const USER_UPDATE_SUCCEEDED = "USER_UPDATE_SUCCEEDED"
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED"

export const USER_DELETE_REQUESTED = "USER_DELETE_REQUESTED"
export const USER_DELETE_SUCCEEDED = "USER_DELETE_SUCCEEDED"
export const USER_DELETE_FAILED = "USER_DELETE_FAILED"